src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $art_nom;

    /**
     * @ORM\Column(type="text")
     */
    private $descri;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $photo;

    /**
     * @ORM\Column(type="float", scale=2)
     */
    private $prix;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cat1;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cat2;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $top = 0;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getArtNom(): ?string
    {
        return $this->art_nom;
    }

    public function setArtNom(string $art_nom): self
    {
        $this->art_nom = $art_nom;

        return $this;
    }

    public function getDescri(): ?string
    {
        return $this->descri;
    }

    public function setDescri(string $descri): self
    {
        $this->descri = $descri;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getCat1(): ?string
    {
        return $this->cat1;
    }

    public function setCat1(string $cat1): self
    {
        $this->cat1 = $cat1;

        return $this;
    }

    public function getCat2(): ?string
    {
        return $this->cat2;
    }

    public function setCat2(?string $cat2): self
    {
        $this->cat2 = $cat2;

        return $this;
    }

    public function getTop(): ?bool
    {
        return $this->top;
    }

    public function setTop(?bool $top): self
    {
        $this->top = $top;

        return $this;
    }
}

src/Entity/Livraison.php
<?php

namespace App\Entity;

use App\Repository\LivraisonRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LivraisonRepository::class)
 */
class Livraison
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $denomination;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $add_nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $add_prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $complement;

    /**
     * @ORM\Column(type="integer", length=5)
     */
    private $cp;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $add_civilite;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDenomination(): ?string
    {
        return $this->denomination;
    }

    public function setDenomination(string $denomination): self
    {
        $this->denomination = $denomination;

        return $this;
    }

    public function getAddNom(): ?string
    {
        return $this->add_nom;
    }

    public function setAddNom(string $add_nom): self
    {
        $this->add_nom = $add_nom;

        return $this;
    }

    public function getAddPrenom(): ?string
    {
        return $this->add_prenom;
    }

    public function setAddPrenom(string $add_prenom): self
    {
        $this->add_prenom = $add_prenom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getComplement(): ?string
    {
        return $this->complement;
    }

    public function setComplement(?string $complement): self
    {
        $this->complement = $complement;

        return $this;
    }

    public function getCp(): ?int
    {
        return $this->cp;
    }

    public function setCp(int $cp): self
    {
        $this->cp = $cp;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getAddCivilite(): ?string
    {
        return $this->add_civilite;
    }

    public function setAddCivilite(string $add_civilite): self
    {
        $this->add_civilite = $add_civilite;

        return $this;
    }
}

src/Entity/UserLivraison.php
<?php

namespace App\Entity;

use App\Repository\UserLivraisonRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=UserLivraisonRepository::class)
 */
class UserLivraison
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $livraison_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $user_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLivraisonId(): ?int
    {
        return $this->livraison_id;
    }

    public function setLivraisonId(int $livraison_id): self
    {
        $this->livraison_id = $livraison_id;

        return $this;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }
}

src/Form/LivraisonType.php
<?php

namespace App\Form;

use App\Entity\Livraison;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Validator\Constraints as Assert;

class LivraisonType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('denomination', TextType::class, [
                'label' => 'Nom de l\'adresse',
                'attr' => [
                    'placeholder' => 'Ex.: Chez moi' 
                ]
            ])
            ->add('addCivilite', ChoiceType::class, [
                'label' => 'Civilité',
                'choices' => [
                    'Monsieur' => 'monsieur',
                    'Madame' => 'madame',
                ]
            ])
            ->add('addNom', TextType::class, [
                'label' => 'Nom',
                'attr' => [
                    'placeholder' => 'Ex.: Dupont'
                ],
                'constraints' => [
                    new Assert\Regex([
                        'pattern' => '/\d/',
                        'match' => false,
                        'message' => 'Votre nom ne peut pas contenir de nombre',
                    ])
                ]
            ])
            ->add('addPrenom', TextType::class, [
                'label' => 'Prénom',
                'attr' => [
                    'placeholder' => 'Ex.: Jean'
                ],
                'constraints' => [
                    new Assert\Regex([
                        'pattern' => '/\d/',
                        'match' => false,
                        'message' => 'Votre prénom ne peut pas contenir de nombre',
                    ])
                ]
            ])
            ->add('adresse', TextType::class , [
                'label' => 'Adresse',
                'attr' => [
                    'placeholder' => 'Ex.: 10 rue du Village'
                ]
            ])
            ->add('complement', TextType::class , [
                'label' => 'Complément',
                'required' => false,
                'attr' => [
                    'placeholder' => 'batiment, étage, digicode, ...'
                ]
            ])
            ->add('cp', IntegerType::class, [
                'label' => 'Code postal',
                'attr' => [
                    'placeholder' => 'Ex.: 67100',
                    'min' => 1000,
                    'max' => 99999
                ],
            ])
            ->add('ville', TextType::class, [
                'label' => 'Ville',
                'attr' => [
                    'placeholder' => 'Ex.: Strasbourg'
                ]
            ])
            ->add('valider', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Livraison::class,
        ]);
    }
}

src/Controller/LivraisonController.php
<?php

namespace App\Controller;

use App\Entity\Livraison;
use App\Form\LivraisonType;
use App\Entity\UserLivraison;
use App\Repository\ArticleRepository;
use App\Repository\LivraisonRepository;
use App\Repository\UserLivraisonRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class LivraisonController extends AbstractController
{
    /**
     * @Route("/livraison", name="livraison")
     */
    public function index(LivraisonRepository $livraisonRepository, UserLivraisonRepository $userLivraisonRepository, ArticleRepository $articleRepository, SessionInterface $session): Response
    {
        $adresses_id = $userLivraisonRepository->findAdresses($this->getUser()->getId());
        $adresses = $livraisonRepository->findAll();

        $panier = $session->get('panier', []);
        $panierRempli = [];
        
        foreach ($panier as $id => $quantite)
        {
            $panierRempli[] = [
                'article' => $articleRepository->find($id),
                'quantite' => $quantite
            ];
        }
        
        $total = 0;
        
        foreach ($panierRempli as $item)
        {
            $totalItem = $item['article']->getPrix() * $item['quantite'];
            $total += $totalItem;
        }
        
        return $this->render('livraison/index.html.twig', [
            'adresses_id' => $adresses_id,
            'adresses' => $adresses,
            'items' => $panierRempli,
            'total' => $total
        ]);
    }

    /**
     * @Route("/livraison/create", name="livraison_create")
     */
    public function createAdresse(Request $request)
    {
        $livraison = new Livraison();
        $user_livraison = new UserLivraison();
        $form = $this->createForm(LivraisonType::class, $livraison);
        $form->handleRequest($request);
        if ($form->isSubmitted()) 
        {
            if ($form->isValid())
            {
                $manager = $this->getDoctrine()->getManager();
                $manager->persist($livraison);
                $manager->flush();
                
                $user_livraison->setLivraisonId($livraison->getId());
                $user_livraison->setUserId($this->getUser()->getId());
                $manager->persist($user_livraison);
                $manager->flush();

                $this->addFlash('success', 'L\'adresse a bien été ajoutée.');
            }
            else
                $this->addFlash('danger','Une erreur est survenue lors de l\'ajout de l\'adresse.');
                
            return $this->redirectToRoute('livraison');
        }
        return $this->render('livraison/livraisonForm.html.twig', [
            'livraisonForm' => $form->createView()
        ]);
    }

    /**
     * @Route("/livraison/update-{id}", name="livraison_update")
     */
    public function updateLivraison(LivraisonRepository $livraisonRepository, $id, Request $request)
    {
        $livraison = $livraisonRepository->find($id);
        $form = $this->createForm(LivraisonType::class, $livraison);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid())
        {
            $manager = $this->getDoctrine()->getManager();
            $manager->persist($livraison);
            $manager->flush();

            $this->addFlash('success', 'L\'adresse a bien été modifiée.');

            return $this->redirectToRoute('livraison');
        }
        return $this->render('livraison/livraisonForm.html.twig', [
            'livraisonForm' => $form->createView()
        ]);
    }
}

templates/livraison/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PanierController!{% endblock %}

{% block body %}

<div class="container p-5">
    <div class="row">
        <div class="col-12">
            {% for label, messages in app.flashes(['success', 'danger']) %}
                {% for message in messages %}
                    <div class="flash-{{ label }} bg-{{ label }} text-light p-3 mb-3 rounded">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endfor %}
        </div>

        <div class="col-12">
            <h2 class="p-3">Votre commande</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th>Produit</th>
                        <th>Prix</th>
                        <th>Quantité</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in items %}
                        <tr>
                            <td>{{ item.article.artNom }}</td>
                            <td>{{ item.article.prix }} €</td>
                            <td>{{ item.quantite }}</td>
                            <td>{{ item.quantite * item.article.prix }} €</td>
                        </tr>
                    {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                        <td class="text-right" colspan="3">Total : </td>
                        <td>{{ total }} €</td>
                    </tr>
                </tfoot>
            </table>
        </div>
        <div class="col-12">
            {% if (adresses_id) %}
                {% for adresse_id in adresses_id %}
                    {% for adresse in adresses %}
                        {% if (adresse.id == adresse_id.livraisonId) %}
                            <div class="col-12">
                                <h2 class="p-3">Adresse de livraison</h2>
                            </div>
                            <div class="col-12">
                                <h3 class="p-3">{{ adresse.denomination }}</h3>
                            </div>
                            <div class="row">
                                <div class="col-6">
                                    <ul>
                                        <li>Civilité :</li>
                                        <li>Nom :</li>
                                        <li>Prénom :</li>
                                        <li>Adresse :</li>
                                        {% if adresse.complement %}
                                            <li>Complément :</li>
                                        {% endif %}
                                        <li>Code postal :</li>
                                        <li>Ville :</li>
                                    </ul>
                                </div>

                                <div class="col-6">
                                    <ul>
                                        <li>{{ adresse.addCivilite|capitalize }}</li>
                                        <li>{{ adresse.addNom|capitalize }}</li>
                                        <li>{{ adresse.addPrenom|capitalize }}</li>
                                        <li>{{ adresse.adresse }}</li>
                                        {% if adresse.complement %}
                                            <li>{{ adresse.complement }}</li>
                                        {% endif %}
                                        <li>{{ adresse.cp }}</li>
                                        <li>{{ adresse.ville|capitalize }}</li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-12 text-center p-3">
                                <a href="{{ path('livraison_update', {'id':adresse.id}) }}"><button class="btn btn-light btn-outline-dark">Modifier l'adresse</button></a>
                            </div>

                            <div class="col-12 text-right p-3">
                                <a href="{{ path('order', {'adresse_id':adresse.id}) }}"><button class="btn btn-primary">Etape suivante</button></a>
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            {% else %}
                <div class="col-12 text-center p-3">
                    <a href="{{ path('livraison_create') }}"><button class="btn btn-light btn-outline-dark">Ajouter une adresse de livraison</button></a>
                </div>
            {% endif %}

        </div>
    </div>
</div>

{% endblock %}

templates/livraison/livraisonForm.html.twig
{% extends 'base.html.twig' %}

{% block title %}Utilisateur - Modification de l'adresse{% endblock title %}

{% block body %}

    {{ form_start(livraisonForm) }}

        <div class="container p-5">
            <h2 class="pb-5">Modification de l'adresse de livraison</h2>
            <div class="row">
                <div class="col-12 my-3">
                    {{ form_label(livraisonForm.denomination) }}
                    {{ form_widget(livraisonForm.denomination) }}
                </div>

                <div class="col-12 my-3">
                    {{ form_label(livraisonForm.addCivilite) }}
                    {{ form_widget(livraisonForm.addCivilite) }}
                </div>

                <div class="col-12 my-3">
                    {{ form_label(livraisonForm.addNom) }}
                    {{ form_widget(livraisonForm.addNom) }}
                </div>
                
                <div class="col-12 my-3">
                    {{ form_label(livraisonForm.addPrenom) }}
                    {{ form_widget(livraisonForm.addPrenom) }}
                </div>
                
                <div class="col-12 my-3">
                    {{ form_label(livraisonForm.adresse) }}
                    {{ form_widget(livraisonForm.adresse) }}
                </div>

                <div class="col-12 my-3">
                    {{ form_label(livraisonForm.complement) }}
                    {{ form_widget(livraisonForm.complement) }}
                </div>

                <div class="col-12 my-3">
                    {{ form_label(livraisonForm.cp) }}
                    {{ form_widget(livraisonForm.cp) }}
                </div>

                <div class="col-12 my-3">
                    {{ form_label(livraisonForm.ville) }}
                    {{ form_widget(livraisonForm.ville) }}
                </div>

                <div class="col-12 text-center">
                    {{ form_widget(livraisonForm.valider )}}
                </div>
                
            </div>
        </div>
    {{ form_end(livraisonForm) }}

{% endblock %}