src/Entity/Livraison.php
<?php

namespace App\Entity;

use App\Repository\LivraisonRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LivraisonRepository::class)
 */
class Livraison
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $denomination;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $add_nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $add_prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $complement;

    /**
     * @ORM\Column(type="integer", length=5)
     */
    private $cp;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $add_civilite;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDenomination(): ?string
    {
        return $this->denomination;
    }

    public function setDenomination(string $denomination): self
    {
        $this->denomination = $denomination;

        return $this;
    }

    public function getAddNom(): ?string
    {
        return $this->add_nom;
    }

    public function setAddNom(string $add_nom): self
    {
        $this->add_nom = $add_nom;

        return $this;
    }

    public function getAddPrenom(): ?string
    {
        return $this->add_prenom;
    }

    public function setAddPrenom(string $add_prenom): self
    {
        $this->add_prenom = $add_prenom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getComplement(): ?string
    {
        return $this->complement;
    }

    public function setComplement(?string $complement): self
    {
        $this->complement = $complement;

        return $this;
    }

    public function getCp(): ?int
    {
        return $this->cp;
    }

    public function setCp(int $cp): self
    {
        $this->cp = $cp;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getAddCivilite(): ?string
    {
        return $this->add_civilite;
    }

    public function setAddCivilite(string $add_civilite): self
    {
        $this->add_civilite = $add_civilite;

        return $this;
    }
}

src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\Table(name="`order`")
 */
class Order
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $numero;

    /**
     * @ORM\Column(type="float", scale=2)
     */
    private $somme;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_livraison;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse_livraison;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $moyen_paiement;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $statut;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $memo;

    /**
     * @ORM\Column(type="integer")
     */
    private $cart_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $user_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumero(): ?string
    {
        return $this->numero;
    }

    public function setNumero(string $numero): self
    {
        $this->numero = $numero;

        return $this;
    }

    public function getSomme(): ?float
    {
        return $this->somme;
    }

    public function setSomme(float $somme): self
    {
        $this->somme = $somme;

        return $this;
    }

    public function getDateLivraison(): ?\DateTimeInterface
    {
        return $this->date_livraison;
    }

    public function setDateLivraison(\DateTimeInterface $date_livraison): self
    {
        $this->date_livraison = $date_livraison;

        return $this;
    }

    public function getAdresseLivraison(): ?string
    {
        return $this->adresse_livraison;
    }

    public function setAdresseLivraison(string $adresse_livraison): self
    {
        $this->adresse_livraison = $adresse_livraison;

        return $this;
    }

    public function getMoyenPaiement(): ?string
    {
        return $this->moyen_paiement;
    }

    public function setMoyenPaiement(string $moyen_paiement): self
    {
        $this->moyen_paiement = $moyen_paiement;

        return $this;
    }

    public function getMemo(): ?string
    {
        return $this->memo;
    }

    public function setMemo(string $memo): self
    {
        $this->memo = $memo;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getCartId(): ?int
    {
        return $this->cart_id;
    }

    public function setCartId(int $cart_id): self
    {
        $this->cart_id = $cart_id;

        return $this;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $civilite;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $phone;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $current_livraison_id;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getCivilite(): ?string
    {
        return $this->civilite;
    }

    public function setCivilite(string $civilite): self
    {
        $this->civilite = $civilite;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getCurrentLivraisonId(): ?int
    {
        return $this->current_livraison_id;
    }

    public function setCurrentLivraisonId(?int $current_livraison_id): self
    {
        $this->current_livraison_id = $current_livraison_id;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
}

src/Entity/UserLivraison.php
<?php

namespace App\Entity;

use App\Repository\UserLivraisonRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=UserLivraisonRepository::class)
 */
class UserLivraison
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $livraison_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $user_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLivraisonId(): ?int
    {
        return $this->livraison_id;
    }

    public function setLivraisonId(int $livraison_id): self
    {
        $this->livraison_id = $livraison_id;

        return $this;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Rollerworks\Component\PasswordStrength\Validator\Constraints\PasswordStrength;
use Symfony\Component\Validator\Constraints as Assert;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('civilite', ChoiceType::class, [
                'choices' => [
                    'Monsieur' => 'monsieur',
                    'Madame' => 'madame',
                ],
                'label' => 'Civilité'
            ])

            ->add('nom', TextType::class, [
                'label' => 'Nom',
                'constraints' => [
                    new Assert\Regex([
                        'pattern' => '/\d/',
                        'match' => false,
                        'message' => 'Votre nom ne peut pas contenir de nombre',
                    ])
                ]
            ])

            ->add('prenom', TextType::class, [
                'label' => 'Prénom',
                'constraints' => [
                    new Assert\Regex([
                        'pattern' => '/\d/',
                        'match' => false,
                        'message' => 'Votre prénom ne peut pas contenir de nombre',
                    ])
                ]
            ])

            ->add('phone', IntegerType::class, [
                'attr' => [
                    'placeholder' => '0123456789',
                    'max' => 999999999999
                ],
                'label' => 'Téléphone'
            ])

            ->add('email', EmailType::class, [
                'required' => false,
            ])

            ->add('plainPassword', PasswordType::class, [
                'mapped' => false,
                'constraints' => [
                    new PasswordStrength([
                        'minLength' => 8,
                        'tooShortMessage' => 'Le mot de passe doit contenir au moins 8 caractères',
                        'minStrength' => 4,
                        'message' => 'Le mot de passe doit contenir au moins une lettre minuscule, une lettre majuscule, un chiffre et un caractère spécial'
                        ])
                ],
                'attr' => [
                    'placeholder' => '••••••••'
                ],
                'label' => 'Mot de passe',
                'required' => false
            ])
                    
            ->add('valider', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Form\UserType;
use App\Repository\UserRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class UserController extends AbstractController
{
    /**
     * @Route("/user", name="user")
     */
    public function index(): Response
    {
        return $this->render('user/index.html.twig', [
            'controller_name' => 'UserController',
        ]);
    }

    /**
     * @Route("/user/update-{id}", name="user_update")
     */
    public function updateUser(UserRepository $userRepository, $id, Request $request, UserPasswordEncoderInterface $passwordEncoder)
    {
        $user = $userRepository->find($id);
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid())
        {
            if ($form['plainPassword']->getData())
            {
                $user->setPassword(
                    $passwordEncoder->encodePassword(
                        $user,
                        $form->get('plainPassword')->getData()
                        )
                    );
            }

            $manager = $this->getDoctrine()->getManager();
            $manager->persist($user);
            $manager->flush();

            $this->addFlash('success', 'Vos informations ont bien été modifiées.');

            return $this->redirectToRoute('user');
        }
        return $this->render('user/userForm.html.twig', [
            'userForm' => $form->createView(),
        ]);
    }
}

templates/user/adresseForm.html.twig
{% extends 'base.html.twig' %}

{% block title %}Utilisateur - Modification de l'adresse{% endblock title %}

{% block body %}

    {{ form_start(adresseForm) }}

        <div class="container p-5">
            <h2 class="pb-5">Modification de l'adresse</h2>
            <div class="row">
                <div class="col-12 my-3">
                    {{ form_label(adresseForm.denomination) }}
                    {{ form_widget(adresseForm.denomination) }}
                </div>

                <div class="col-12 my-3">
                    {{ form_label(adresseForm.addCivilite) }}
                    {{ form_widget(adresseForm.addCivilite) }}
                </div>

                <div class="col-12 my-3">
                    {{ form_label(adresseForm.addNom) }}
                    {{ form_widget(adresseForm.addNom) }}
                </div>
                
                <div class="col-12 my-3">
                    {{ form_label(adresseForm.addPrenom) }}
                    {{ form_widget(adresseForm.addPrenom) }}
                </div>
                
                <div class="col-12 my-3">
                    {{ form_label(adresseForm.adresse) }}
                    {{ form_widget(adresseForm.adresse) }}
                </div>

                <div class="col-12 my-3">
                    {{ form_label(adresseForm.complement) }}
                    {{ form_widget(adresseForm.complement) }}
                </div>

                <div class="col-12 my-3">
                    {{ form_label(adresseForm.cp) }}
                    {{ form_widget(adresseForm.cp) }}
                </div>

                <div class="col-12 my-3">
                    {{ form_label(adresseForm.ville) }}
                    {{ form_widget(adresseForm.ville) }}
                </div>

                <div class="col-12 text-center">
                    {{ form_widget(adresseForm.valider )}}
                </div>
                
            </div>
        </div>
    {{ form_end(adresseForm) }}

{% endblock %}

templates/user/adresses.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adresses utilisateur{% endblock %}

{% block body %}

{% if app.user %}
    <div class="container p-5">
        <div class="row">
            <div class="col-12">
                {% for label, messages in app.flashes(['success', 'danger']) %}
                    {% for message in messages %}
                        <div class="flash-{{ label }} bg-{{ label }} text-light p-3 mb-3 rounded">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endfor %}
            </div>

            <div class="col-3">
                <p><a href="{{ path('user') }}">Informations</a></p>
                <p><a href="{{ path('user_adresses') }}">Adresse</a></p>
                <p><a href="{{ path('user_commandes') }}">Commandes</a></p>
                <p><a href="{{ path('app_logout') }}">Se déconnecter</a></p>
            </div>
            <div class="col-9">
                <h2 class="p-3">Bienvenue {{ app.user.prenom }} !</h2>
                
                <div class="row">
                    <div class="col-12">
                        <h3 class="p-3">Gérer mon adresse</h3>
                    </div>
                    {% if (adresses_id) %}
                        {% for adresse_id in adresses_id %}
                            {% for adresse in adresses %}
                                {% if (adresse.id == adresse_id.livraisonId) %}
                                    <div class="col-12">
                                        <h2 class="p-3">{{ adresse.denomination }}</h2>
                                    </div>

                                    <div class="col-6">
                                        <ul>
                                            <li>Civilité :</li>
                                            <li>Nom :</li>
                                            <li>Prénom :</li>
                                            <li>Adresse :</li>
                                            {% if adresse.complement %}
                                                <li>Complément :</li>
                                            {% endif %}
                                            <li>Code postal :</li>
                                            <li>Ville :</li>
                                        </ul>
                                    </div>

                                    <div class="col-6">
                                        <ul>
                                            <li>{{ adresse.addCivilite|capitalize }}</li>
                                            <li>{{ adresse.addNom|capitalize }}</li>
                                            <li>{{ adresse.addPrenom|capitalize }}</li>
                                            <li>{{ adresse.adresse }}</li>
                                            {% if adresse.complement %}
                                                <li>{{ adresse.complement }}</li>
                                            {% endif %}
                                            <li>{{ adresse.cp }}</li>
                                            <li>{{ adresse.ville|capitalize }}</li>
                                        </ul>
                                    </div>

                                    {# Si plusieurs adresses gérées #}
                                    {# <div class="col-12 p-3">
                                        <a href="{{ path('adresse_delete', {'id':adresse_id.id}) }}"><button class="btn btn-danger btn-sm">Supprimer cette adresse</button></a>
                                    </div> #}

                                    <div class="col-12 text-center p-3">
                                        <a href="{{ path('adresse_update', {'id':adresse.id}) }}"><button class="btn btn-light btn-outline-dark">Modifier l'adresse</button></a>
                                    </div>

                                {% endif %}
                            {% endfor %}
                        {% endfor %}
                    {% else %}
                        <div class="col-12 text-center p-3">
                            <a href="{{ path('adresse_create') }}"><button class="btn btn-light btn-outline-dark">Ajouter une adresse</button></a>
                        </div>
                    {% endif %}      
                </div>
            </div>
        </div>
    </div>
{% else %}
    <div class="container text-center p-5">
        <h3 class="pb-5">Vous devez vous connecter pour accéder à votre compte.</h3>
        <a href="{{ path('app_login') }}"><button class="btn btn-light btn-outline-dark">Se connecter</button></a>
        <a href="{{ path('app_register') }}"><button class="btn btn-light btn-outline-dark">Créer un compte</button></a>
    </div>
        
{% endif %}
{% endblock %}

templates/user/commandes.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commandes utilisateur{% endblock %}

{% block body %}

{% if app.user %}
    <div class="container p-5">
        <div class="row">
            <div class="col-3">
                <p><a href="{{ path('user') }}">Informations</a></p>
                <p><a href="{{ path('user_adresses') }}">Adresse</a></p>
                <p><a href="{{ path('user_commandes') }}">Commandes</a></p>
                <p><a href="{{ path('app_logout') }}">Se déconnecter</a></p>
            </div>
            <div class="col-9">
                <h2 class="p-3">Bienvenue {{ app.user.prenom }} !</h2>
                
                <div class="row">
                    <div class="col-12">
                        <h3 class="p-3">Historique des commandes</h3>
                    </div>
                    
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Numéro</th>
                                <th>Prix</th>
                                <th>Date de livraison</th>
                                <th>Adresse de livraison</th>
                                <th>Moyen de paiement</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for commande in commandes %}
                                <tr>
                                    <td>{{ commande.numero }}</td>
                                    <td>{{ commande.somme }} €</td>
                                    <td>{{ commande.dateLivraison|date(('Y-m-d H:i')) }}</td>
                                    <td>{{ commande.adresseLivraison }}</td>
                                    <td>{{ commande.moyenPaiement }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
{% else %}
    <div class="container text-center p-5">
        <h3 class="pb-5">Vous devez vous connecter pour accéder à votre compte.</h3>
        <a href="{{ path('app_login') }}"><button class="btn btn-light btn-outline-dark">Se connecter</button></a>
        <a href="{{ path('app_register') }}"><button class="btn btn-light btn-outline-dark">Créer un compte</button></a>
    </div>
        
{% endif %}
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}

{% if app.user %}
    <div class="container p-5">
        <div class="row">
            <div class="col-12">
                {% for label, messages in app.flashes(['success', 'danger']) %}
                    {% for message in messages %}
                        <div class="flash-{{ label }} bg-{{ label }} text-light p-3 mb-3 rounded">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endfor %}
            </div>

            <div class="col-3">
                <p><a href="{{ path('user') }}">Informations</a></p>
                <p><a href="{{ path('user_adresses') }}">Adresse</a></p>
                <p><a href="{{ path('user_commandes') }}">Commandes</a></p>
                <p><a href="{{ path('app_logout') }}">Se déconnecter</a></p>
            </div>
            <div class="col-9">
                <h2 class="p-3">Bienvenue {{ app.user.prenom }} !</h2>
                
                <div class="row">
                    <div class="col-12">
                        <h3 class="p-3">Informations du compte</h3>
                    </div>
                    <div class="col-6">
                        <ul>
                            <li>Civilité :</li>
                            <li>Nom :</li>
                            <li>Prénom :</li>
                            <li>Téléphone :</li>
                            <li>Email :</li>
                        </ul>
                    </div>

                    <div class="col-6">
                        <ul>
                            <li>{{ app.user.civilite|capitalize }}</li>
                            <li>{{ app.user.nom|capitalize }}</li>
                            <li>{{ app.user.prenom|capitalize }}</li>
                            <li>{{ app.user.phone }}</li>
                            <li>{{ app.user.email }}</li>
                        </ul>
                    </div>

                    <div class="col-12 text-center p-3">
                        <a href="{{ path('user_update', {'id':app.user.id}) }}"><button class="btn btn-light btn-outline-dark">Modifier mes informations</button></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% else %}
    <div class="container text-center p-5">
        <h3 class="pb-5">Vous devez vous connecter pour accéder à votre compte.</h3>
        <a href="{{ path('app_login') }}"><button class="btn btn-light btn-outline-dark">Se connecter</button></a>
        <a href="{{ path('app_register') }}"><button class="btn btn-light btn-outline-dark">Créer un compte</button></a>
    </div>
        
{% endif %}
{% endblock %}

templates/user/userForm.html.twig
{% extends 'base.html.twig' %}

{% block title %}Utilisateur - Modification du compte{% endblock title %}

{% block body %}

    {{ form_start(userForm) }}

        <div class="container p-5">
            <h2 class="pb-5">Modification du compte</h2>
            <div class="row">
                <div class="col-6 my-3">
                    {{ form_label(userForm.civilite) }}
                    {{ form_widget(userForm.civilite) }}
                </div>

                <div class="col-6 my-3">
                    {{ form_label(userForm.nom) }}
                    {{ form_widget(userForm.nom) }}
                </div>
                
                <div class="col-6 my-3">
                    {{ form_label(userForm.prenom) }}
                    {{ form_widget(userForm.prenom) }}
                </div>
                
                <div class="col-6 my-3">
                    {{ form_label(userForm.phone) }}
                    {{ form_widget(userForm.phone) }}
                </div>

                <div class="col-6 my-3">
                    {{ form_label(userForm.email) }}
                    {{ form_widget(userForm.email) }}
                </div>

                <div class="col-6 my-3">
                    {{ form_label(userForm.plainPassword) }}
                    {{ form_widget(userForm.plainPassword) }}
                </div>

                <div class="col-12 text-center">
                    {{ form_widget(userForm.valider )}}
                </div>
                
            </div>
        </div>
    {{ form_end(userForm) }}

{% endblock %}